name = "StellarAtmospheres"
uuid = "b683c2a4-e546-4d2a-bd5b-d76733f00fc3"
authors = ["Michael Palumbo <mlp95@psu.edu>"]
version = "0.1.0"

[deps]
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
PyPlot = "d330b81b-6aea-500a-939a-2ce795aea3ee"
